### ISSUE TITLE
R CMD check --as-cran

### ISSUE THREAD

**Issue by katehoffshutta** [QuackenbushLab/NetworkDataCompanion#52]
Various errors for installation will need to be solved before the package can be submitted to CRAN; see #49 for details.

**Comment by soelmicheletti** [comment]
I refactored a lot of small things, it should work now. 

- R CMD check . --as-cran works on my machine
- The GitHub action is green (it runs the checks, but not for CRAN)
- I documented the steps for installation and updating the documentation on the README

I will close the issue. If CRAN is different on my machine we can reopen it and fix it.
